### ISSUE TITLE
[Release] Checklist for 0.5.0-beta release 

### ISSUE THREAD

**Issue by nextchamp-saqib** [frappe/insights#9]
### Major ones
- [ ] ~Website~
- [ ] ~SaaS Sign-ups~
- [ ] ~Demo Video~
- [ ] Update Readme
- [x] Documentation - https://frappeinsights.frappe.cloud/docs
- [x] Adding Users / Sign-up flow
    - Forward to framework login page for signups
- [ ] ~Onboarding~
- [x] Home Page
   - Added a *Get Started* page
- [x] Adding a Data Source (?)
- [x] Improve Dashboard Layout Editor

### Minor ones
- [x] Add Format field in Dimension Picker for Date columns
- [x] Add empty states for all lists
- [x] Color Picker for Charts (?)
- [x] Remove unimplemented visualization types
- [x] Increase default size of newly added visualization 
- [x] Expression function help only appears when autocompleted
- [x] Refreshing dashboard doesn't refresh table
- [x] Loading states for dashboard cards
